<?php
/**
 * @file
 * Code for the luggage_story feature.
 */

include_once 'luggage_story.features.inc';

/*
 * Implements hook_preprocess_html.
 */
function luggage_story_preprocess_html(&$vars) {
  // Override suitcase_interim styles for this site.
  global $theme;
  if ($theme == 'suitcase_interim') {
    drupal_add_css(drupal_get_path('module', 'luggage_story') . '/css/luggage_story.css', array('group' => 200));
  }
}